### ISSUE TITLE
Back to problem with starting Amok on Windows 7

### ISSUE THREAD

**Issue by cachaito** [caspervonb/amok#89] opened 2015-07-01 08:10 UTC
Hi @caspervonb !
I tried to run brand new `Amok 1.0.0-4` with global var `CHROME_BIN` with path: `C:\Program Files (x86)\Google\Chrome\Application` (I also provided same path to my `PATH` so command: `chrome` starts the browser) but always getting: 
```
amok --browser chrome app.js
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Bad browser command C:\Program Files (x86)\Google\Chrome\Application
    at Error (native)
```

**Comment by caspervonb** [comment] 2015-07-01 11:27
Hey @cachaito, it's the full path to the executable.` C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`

**Comment by cachaito** [comment] 2015-07-01 11:29
Unfortunately, nope:
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Bad browser command C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
```
:sob:

**Comment by caspervonb** [comment] 2015-07-01 12:44
That path should be default discoverable actually so that's not the issue.
Just checked out the v1.0.0-4 tag on a Windows 7 vm and the browser tests pass.

The npm version tagged 1.0.0-4 gets me different results, very strange

```sh
events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: Cannot read property 'indexOf' of undefined
    at which (C:\Users\caspervonb\AppData\Roaming\npm\node_modules\amok\node_modules\browser_process\node_modules\which\which.js:62:12)
```

I'll assume you ran into this first right?

As for the bad browser command, I think Its's due to the string being unescaped.
The basename of `C:\Program Files (x86)\Google\Chrome\Application\chrome.exe` is actually something like `program files (x86)googleapplicationchrome.exe` which is not recognisable browser.

Got some more digging to do, I'll be back with more info and patches shortly.

**Comment by caspervonb** [comment] 2015-07-02 15:56
The problem is not apparent in master, but master has some other watch issues which is blocking the next release that I'm currently working on, I'll ping this issue when resolved.

**Comment by caspervonb** [comment] 2015-07-05 07:55
The issue was that a patch version that fixed this of `browser_process` was not published to npm, reinstall and this particular issue is resolved. However 1.0.0-4 saw some regressions with script path mapping that I've been working through the weekend, I'll see If I can land them in master tomorrow (refactor/remove-chokidar branch). Today is Sunday and I'm turning 27 so I'm not working ;)

**Comment by stereokai** [comment] 2015-07-05 08:38
Happy birthday! :)

**Comment by cachaito** [comment] 2015-07-05 19:31
Birthday is a saint thing. No work this day! 

Happy birthday! :)

**Comment by caspervonb** [comment] 2015-07-06 20:01
Thanks guys :older_man: 

The actual issue here is fixed so I'm closing this issue, but be advised that there's still a regression for windows in 1.0.0-4 (see #93)

**Closed by caspervonb** 2015-07-06 20:01 UTC
