### ISSUE TITLE
Use of Babel and an index.html doesn't work

### ISSUE THREAD

**Issue by thomaswmanion** [caspervonb/amok#137] opened 2015-08-17 16:10 UTC
Howdy!

I've been trying to figure out a solution to running babel as a compiler inside amok for my JavaScript. Doesn't seem to ever pick up the script file that is generated as the bundle within a tmp folder.
Right now, I'm trying with this, where app/app.js is my bundle entry point and app/index.html is my HTML file.
amok --compiler babel app/app.js -b chrome --hot --interactive --cwd $PWD/app

Whenever I do this, all I receive is "Uncaught SyntaxError: Unexpected reserved word" at my es6 import statement:

    import TopNav from './modules/nav/top-nav';

Any ideas on how to fix this?
Thank you, thank you very much!

Tom

**Comment by caspervonb** [comment] 2015-08-18 02:33
Mind setting `export NODE_DEBUG=amok,amok-compiler` before running and dump the logs here?

**Comment by caspervonb** [comment] 2015-08-18 02:35
Actually, you shouldn't set the cwd to app, and reference scripts inside it. its either or.

**Comment by stereokai** [comment] 2015-08-30 13:39
@thomaswmanion kindly let us know if you've reached a solution? Also please describe it and close the issue if you have. If you need more help, we're here.

**Comment by caspervonb** [comment] 2015-09-11 03:48
Closing this issue as it's been open for about a month without any followup, please feel to post any additional information or open another issue if you still have problems.

I'm 98.5% certain the issue is that cwd is being set but the paths are not relative to that cwd.

**Closed by caspervonb** 2015-09-11 03:48 UTC
