### ISSUE TITLE
Webpack or Browserify doesn't work

### ISSUE THREAD

**Issue by xgrommx** [caspervonb/amok#43] opened 2015-04-03 19:46 UTC
Hello @caspervonb I have tried use webpack together with amok but I got error on this line https://github.com/caspervonb/node-rdbg/blob/master/index.js#L131 as [TypeError: Cannot read property 'apply' of undefined]. For it I use ```console.log(error)``` instead of ```this.error(error);```. For example I use the following code

```js
var React = require('react');

var HelloMessage = React.createClass({displayName: "HelloMessage",
  render: function() {
    return React.createElement("div", null, "Hello ", this.props.name);
  }
});

React.render(React.createElement(HelloMessage, {name: "Denis"}), document.body);
```

And this command ```amok --client chrome --compiler webpack app.js```

**Comment by caspervonb** [comment] 2015-04-04 06:36
Hm am able to run your example on my Linux setup at the very least.
Could you do a quick test that the canvas demo runs?
```
git clone https://gist.github.com/d58c3eecb72ba3dd0846.git examples
cd examples
amok --verbose --client chrome --compiler webpack canvas.js
```

**Comment by deepsweet** [comment] 2015-04-04 13:23
same error here (OSX) even w/o webpack, just `amok --client chrome canvas.js`:

```
/.../amok/node_modules/rdbg/index.js:131
        this.error(error);
             ^
TypeError: undefined is not a function
    at WebSocket.<anonymous> (/.../amok/node_modules/rdbg/index.js:131:14)
    at WebSocket.emit (events.js:110:17)
    at Receiver.ontext (/.../amok/node_modules/rdbg/node_modules/ws/lib/WebSocket.js:798:10)
    at /.../amok/node_modules/rdbg/node_modules/ws/lib/Receiver.js:473:18
    at /.../amok/node_modules/rdbg/node_modules/ws/lib/Receiver.js:357:7
    at /.../amok/node_modules/rdbg/node_modules/ws/lib/PerMessageDeflate.js:217:5
    at afterWrite (_stream_writable.js:361:3)
    at onwrite (_stream_writable.js:352:7)
    at WritableState.onwrite (_stream_writable.js:105:5)
    at afterTransform (_stream_transform.js:99:5)
```

**Comment by deepsweet** [comment] 2015-04-04 13:27
I think it's somehow related to https://github.com/caspervonb/amok/commit/88a60049bd99d2b8100feb5b7cfac3b96959b963, because at first launch amok crashes but leaves chrome instance running. at second launch it spawns one more chrome instance and works fine with it.

**Comment by caspervonb** [comment] 2015-04-04 13:33
Give 0.12.4 a try, fixes the error reporting at-least so we'll get the actual error.

**Comment by caspervonb** [comment] 2015-04-04 13:37
Chrome version might also be relevant

**Comment by deepsweet** [comment] 2015-04-04 13:45
same `undefined is not a function` at `amok/node_modules/rdbg/index.js:131` as above.

```
└─┬ amok@0.12.4
  ├── async@0.9.0
  ├── chokidar@1.0.0-rc5
  ├── commander@2.7.1
  ├── mime@1.3.4
  ├── rdbg@0.3.4
  ├── temp@0.8.1
  └── which@1.0.9
```

Chrome 42.0.2311.68 beta (64-bit).

**Comment by caspervonb** [comment] 2015-04-04 13:57
Should've been an `emit('error', error)`

**Comment by deepsweet** [comment] 2015-04-04 14:14
```
Attaching debugger...
Debugger attached to
events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: Cannot read property 'map' of undefined
    at EventEmitter.<anonymous> (/.../amok/cmd.js:167:42)
    at EventEmitter.emit (events.js:107:17)
    at ChromeConnection._process (/.../amok/node_modules/rdbg/index.js:67:23)
    at WebSocket.<anonymous> (/.../amok/node_modules/rdbg/index.js:129:14)
    at WebSocket.emit (events.js:110:17)
    at Receiver.ontext (/.../amok/node_modules/rdbg/node_modules/ws/lib/WebSocket.js:798:10)
    at /.../amok/node_modules/rdbg/node_modules/ws/lib/Receiver.js:473:18
    at /.../amok/node_modules/rdbg/node_modules/ws/lib/Receiver.js:357:7
    at /.../amok/node_modules/rdbg/node_modules/ws/lib/PerMessageDeflate.js:217:5
    at afterWrite (_stream_writable.js:361:3)
```

**Comment by caspervonb** [comment] 2015-04-04 14:27
Give v0.12.6 a try, can't reproduce so sorry for the back and forth :)

**Comment by deepsweet** [comment] 2015-04-04 14:40
it works :+1:

**Comment by caspervonb** [comment] 2015-04-04 14:57
Great. Appears there are some minor differences in the results from chrome between v41 and v42.

**Comment by deepsweet** [comment] 2015-04-04 15:16
oops.

canvas.js works fine, but not the example with React from issue starter:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: Cannot read property 'apply' of undefined
    at EventEmitter.<anonymous> (/.../amok/cmd.js:172:31)
    at EventEmitter.emit (events.js:107:17)
    at ChromeConnection._process (/.../amok/node_modules/rdbg/index.js:67:23)
    at WebSocket.<anonymous> (/.../amok/node_modules/rdbg/index.js:129:14)
    at WebSocket.emit (events.js:110:17)
    at Receiver.ontext (/.../amok/node_modules/rdbg/node_modules/ws/lib/WebSocket.js:798:10)
    at /.../amok/node_modules/rdbg/node_modules/ws/lib/Receiver.js:473:18
    at /.../amok/node_modules/rdbg/node_modules/ws/lib/Receiver.js:357:7
    at /.../amok/node_modules/rdbg/node_modules/ws/lib/PerMessageDeflate.js:217:5
    at afterWrite (_stream_writable.js:361:3)
```

**Comment by caspervonb** [comment] 2015-04-04 16:15
Should be fixed as of 0.12.7

**Closed by caspervonb** 2015-04-04 16:15 UTC
Labels: question

**Comment by deepsweet** [comment] 2015-04-04 16:17
there are no errors with @0.12.7, but nothing changes until I manually hit the refresh in Chrome.
second attempt gives this:

```
Names
/var/folders/ml/gf29nss96nbcg16zk41p1n7m0000gn/T/amok-output11534-26188-fzj0ye/bundle.js  633 kB       0  [emitted]  main
   [0] ./app.js 286 bytes {0} [built]
    + 156 hidden modules
/var/folders/ml/gf29nss96nbcg16zk41p1n7m0000gn/T/amok-output11534-26188-fzj0ye/bundle.js changed
Re-compiling bundle.js ...
{ code: -32000, message: 'Uncaught Script not found' }
```

**Comment by deepsweet** [comment] 2015-04-04 16:18
can you confirm that

```js
var React = require('react');

var HelloMessage = React.createClass({displayName: "HelloMessage",
  render: function() {
    return React.createElement("div", null, "Hello ", this.props.name);
  }
});

React.render(React.createElement(HelloMessage, {name: "Denis"}), document.body);
```

works fine on your side? changing "Hello " inside render, for example.

**Comment by deepsweet** [comment] 2015-04-04 16:21
I got it.. looks like we need to re-render it manually from `setTimeout` like in this video https://www.youtube.com/watch?v=-aWINzxCNW4

is there a better way to make the magic?

**Comment by caspervonb** [comment] 2015-04-04 16:52
Yes it won't re-render because its strictly without side effects, the definition of the anonymous function referenced by the component's render property is changed, but React.render never gets called again.

setInterval would be the best option for now, something is coming in this space (watch #50)
You could stick it in a seperate file and do --require with browserify, leaving the application as is.

**Comment by caspervonb** [comment] 2015-04-04 17:17
I can confirm that this works on Fedora

```js
var React = require('react');

var HelloMessage = React.createClass({displayName: "HelloMessage",
  render: function() {
    return React.createElement("div", null, "Hello Yo ", this.props.name);
  }
});

setInterval(function() {
  React.render(React.createElement(HelloMessage, {name: "Denis"}), document.body);
}, 500);
```

Ran with 
```sh
amok hello-react.js --client chrome --compiler webpack
```

**Comment by xgrommx** [comment] 2015-04-04 19:06
Could I use this code without ```setTimeout``` like a webpack hot reload? Or I might use a webpack hot reload options with this tool? For example like this https://github.com/gaearon/react-hot-loader
