### ISSUE TITLE
Livereload doesn't work.

### ISSUE THREAD

**Issue by xgrommx** [caspervonb/amok#66] opened 2015-04-14 09:12 UTC
I tried use react-bootstrap of amok-examples. It's very interesting. But will be better add a webpack example. But this is not now. If I add a new dependency like a Panel of react-bootstrap, livereload doesn't work in browser. However when I reload it manual, changes applied but amok thrown error in console. Also is important I made my changes in hot mode without reload amok.

**Comment by xgrommx** [comment] 2015-04-14 13:00
Also the same problem if exist some error in compiler. After fixing their amok livereload doesn't work.

**Comment by caspervonb** [comment] 2015-04-14 18:19
Could you post the `--verbose` logs so i can see what's going on?

**Comment by xgrommx** [comment] 2015-04-14 20:47
Sure. I added a new dependency like a ```Panel``` and I don't see changes in my browser. It's my log after ```--verbose```

```
λ gromm-pc react-bootstrap → λ git master* → npm start                                                                                                            23:42:36

> @ start C:\tmp\amok-examples\react-bootstrap
> amok index.js --verbose --client chrome --compiler browserify -- --transform reactify --fast

 info compile: spawn
 info compile: ok { pid: 10320 }
 info http: starting
 info http: listening { host: '127.0.0.1', port: 9966 }
 info client: spawn
 info client: ok { pid: 4264 }
 info debugger: connect
 info http: GET /index.html
 info debugger: attach { url: 'http://localhost:9966/', title: '' }
 info watch: start
 info http: GET /index.js
 info watch: add { filename: 'C:\\Users\\gromm\\AppData\\Local\\Temp\\amok-output115314-2696-1k5tni5\\index.js' }
 info watch: ok
 info http: GET /favicon.ico
 info watch: add { filename: 'C:\\Users\\gromm\\AppData\\Local\\Temp\\amok-output115314-2696-1k5tni5\\.index.js' }
 info watch: change { filename: 'C:\\Users\\gromm\\AppData\\Local\\Temp\\amok-output115314-2696-1k5tni5\\index.js' }
 info watch: remove { filename: 'C:\\Users\\gromm\\AppData\\Local\\Temp\\amok-output115314-2696-1k5tni5\\.index.js',
  pathname: 'C:\\Users\\gromm\\AppData\\Local\\Temp\\amok-output115314-2696-1k5tni5\\.index.js' }
 info debugger: source { url: 'http://localhost:9966/index.js' }
```

**Comment by xgrommx** [comment] 2015-04-14 20:49
But if I update manual my browser and change some code I got this:

```
info watch: change { filename: 'C:\\Users\\gromm\\AppData\\Local\\Temp\\amok-output115314-2696-1k5tni5\\.index.js' }
 info watch: add { filename: 'C:\\Users\\gromm\\AppData\\Local\\Temp\\amok-output115314-2696-1k5tni5\\.index.js' }
 info watch: change { filename: 'C:\\Users\\gromm\\AppData\\Local\\Temp\\amok-output115314-2696-1k5tni5\\index.js' }
 info watch: remove { filename: 'C:\\Users\\gromm\\AppData\\Local\\Temp\\amok-output115314-2696-1k5tni5\\.index.js',
  pathname: 'C:\\Users\\gromm\\AppData\\Local\\Temp\\amok-output115314-2696-1k5tni5\\.index.js' }
error debugger: Uncaught Script not found
```

**Comment by caspervonb** [comment] 2015-04-14 20:51
The page reload bug will be fixed in the next minor, patched in caspervonb/node-rdbg@c5b48304e235a41186e59dc734009ff0af634283. Was due to duplicate entries in the cache lookup.

Example of what the edit looks like? So i can reproduce.

**Comment by caspervonb** [comment] 2015-04-14 21:07
QW2S

**Comment by xgrommx** [comment] 2015-04-14 21:16
Sure this is my code after changes:

```js
var React = require('react');
var List  = require('./list');
var Input = require('./input');
var Panel = require('react-bootstrap').Panel;

module.exports = React.createClass({
  getInitialState: function() {
    return {items: []}
  },

  addItem: function(itemName) {
    this.setState({items: this.state.items.concat([itemName])})
    return true
  },

  render: function() {
    return (
      <div>
        <Panel header={(<h2>Todo</h2>)}>
          <Input onAdd={this.addItem} />
          <List items={this.state.items} />
        </Panel>
      </div>
    )
  }
})
```

**Comment by xgrommx** [comment] 2015-04-14 21:17
Also I use iojs

**Comment by caspervonb** [comment] 2015-04-14 21:29
Panel in that context would be undefined.

This works.
```js
var React = require('react');
var List  = require('./list');
var Input = require('./input');


module.exports = React.createClass({
  getInitialState: function() {
    return {items: []}
  },

  addItem: function(itemName) {
    this.setState({items: this.state.items.concat([itemName])})
    return true
  },

  render: function() {
    var Panel = require('react-bootstrap').Panel;

    return (
      <div>
        <Panel header={(<h2>Todo</h2>)}>
          <Input onAdd={this.addItem} />
          <List items={this.state.items} />
        </Panel>
      </div>
    )
  }
})
```

**Comment by xgrommx** [comment] 2015-04-14 21:36
Hm... Why this code doesn't work if I define ```Panel``` on top? But if I update browser manual my change applied.

**Comment by caspervonb** [comment] 2015-04-14 21:48
No execution takes place, so while it is a defined variable it hasn't evaluated to the result of require because it was put in after the script was evaluated.

**Closed** 2015-04-15 03:44 UTC

**Comment by xgrommx** [comment] 2015-04-15 10:04
@caspervonb But why it working correct in webpack?

**Comment by caspervonb** [comment] 2015-04-15 12:20
@xgrommx what do you mean?

**Comment by xgrommx** [comment] 2015-04-15 14:13
@caspervonb I mean if I use webpack and define my ```Panel``` on top that livereload working correct.

**Comment by caspervonb** [comment] 2015-04-17 06:29
With HRM?
