### ISSUE TITLE
Cant run on osx

### ISSUE THREAD

**Issue by NetanelBasal** [caspervonb/amok#40] opened 2015-04-03 09:51 UTC
When i type ```amok main.js``` i get this:
```
amok main.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

**Comment by caspervonb** [comment] 2015-04-03 10:01
Duplicate of #31

Thanks for taking the time to report, aiming to have v0.12 out later today or so which simplifies usage by *quite a lot*.

**Closed by caspervonb** 2015-04-03 10:01 UTC
Labels: duplicate
